server:
  port: 8888           # Port standard du Config Server

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        # Option A : Lire les configs depuis un dossier local
        #native:
#          search-locations: classpath:/configurations
        # Option B : Lire depuis un repo Git (recommandé en prod)
        git:
           uri: https://github.com/Idrissa-wedbiga/Config-server
        #   default-label: main
        clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: health, info