server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=/api/auth/**
            filters:
              - StripPrefix=1

          - id: billing-service
            uri: lb://billing-service        # ← uri manquant !
            predicates:
              - Path=/api/billing/**          # ← faute corrigée
            filters:
              - StripPrefix=1

          - id: delivery-service
            uri: lb://delivery-service        # ← uri manquant !
            predicates:
              - Path=/api/delivery/**
            filters:
              - StripPrefix=1

          - id: product-service
            uri: lb://product-service         # ← uri manquant !
            predicates:
              - Path=/api/products/**         # ← products avec s
            filters:
              - StripPrefix=1

          - id: stock-service
            uri: lb://stock-service           # ← uri manquant !
            predicates:
              - Path=/api/stock/**
            filters:
              - StripPrefix=1



eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-exlu.onrender.com/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:api-gateway}
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443

jwt:
  secret: cle-secrete-partagee-256bits

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, metrics

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        #url: /api/auth/api-docs  # ← via la Gateway
        url: https://auth-service-d6zt.onrender.com/api-docs
      - name: Product Service
        url: /api/products/v3/api-docs
      - name: Stock Service
        url: /api/stock/v3/api-docs
      - name: Billing Service
        url: /api/billing/v3/api-docs
      - name: Delivery Service
        #url: /api/delivery/v3/api-docs
        url: https://servicelivraison.pythonanywhere.com/apidocs/
  api-docs:
    enabled: true