server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: https://auth-service-d6zt.onrender.com
            predicates:
              - Path=/api/auth/**
            filters:
              - StripPrefix=1

          - id: billing-service
            uri: lb://billing-service
            predicates:
              - Path=/api/billing/**
            filters:
              - StripPrefix=1

          - id: delivery-service
            uri: https://servicelivraison.pythonanywhere.com
            predicates:
              - Path=/api/delivery/**
            filters:
              - StripPrefix=1

          - id: product-service
            uri: https://product-service-production-2d82.up.railway.app
            predicates:
              - Path=/api/products/**
            filters:
              - StripPrefix=1

          - id: stock-service
            uri: lb://stock-service
            predicates:
              - Path=/api/stock/**
            filters:
              - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:4200"
              - "https://product-service-production-2d82.up.railway.app"
              - "https://servicelivraison.pythonanywhere.com"
              - "https://auth-service-d6zt.onrender.com"
#              - "https://votre-app-angular.onrender.com"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-exlu.onrender.com/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    non-secure-port-enabled: true
    secure-port-enabled: false

jwt:
  secret: cle-secrete-partagee-256bits

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, metrics

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /api/auth/api-docs
      - name: Product Service
        url: /api/products/v3/api-docs
      - name: Stock Service
        url: /api/stock/v3/api-docs
      - name: Billing Service
        url: /api/billing/v3/api-docs
      - name: Delivery Service
        url: https://servicelivraison.pythonanywhere.com/apidocs/
  api-docs:
    enabled: true