spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-exlu.onrender.com/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    non-secure-port-enabled: true
    secure-port-enabled: false
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/info
    health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
    home-page-url: http://${spring.cloud.client.ip-address}:${server.port}/