spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-exlu.onrender.com/eureka/
  instance:
    prefer-ip-address: false
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
    secure-port-enabled: true
    non-secure-port-enabled: false
    secure-port: 443
    status-page-url: https://${eureka.instance.hostname}/actuator/info
    health-check-url: https://${eureka.instance.hostname}/actuator/health
    home-page-url: https://${eureka.instance.hostname}/